// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​S​v​e​l​t​e​K​i​t
	 */
	HI: string
	LOCALES: {
		/**
		 * C​h​a​n​g​e​ ​l​a​n​g​u​a​g​e
		 */
		description: string
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * E​s​p​a​ñ​o​l
		 */
		es: string
	}
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​'​{​f​i​l​e​N​a​m​e​}​'
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
}

export type TranslationFunctions = {
	/**
	 * Welcome to SvelteKit
	 */
	HI: () => LocalizedString
	LOCALES: {
		/**
		 * Change language
		 */
		description: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Español
		 */
		es: () => LocalizedString
	}
	/**
	 * This log was called from '{fileName}'
	 */
	log: (arg: { fileName: string }) => LocalizedString
}

export type Formatters = {}
